### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by grzhan** [synyi/annotation-tool#1]
### Version 0.1.1
- [x] feature: support clean up (clear all svg elements)
- [x] feature: make initial render async 
- [x] feature: auto left padding
### Version 0.2.0

feature: relation
- [x] detect relation label's collision
- [x] draw arrow
- [x] handle situation: relation text label is wider than related label's distance
- [x] async render relations while importing
- [x] connect two annotated labels by dragging
### Version 0.3.0

span multi-lines
- [x] label: span multi-lines
- [x] compatibility: firefox
- [x] rendering failed occasionally
### Version 0.4.0
- [ ] ~load optimization~
- [ ] ~annotate paragraph~
- [ ] ~Safari: crash while exporting PNG image~
### Refactor
- [ ] ~FE workflow: integrate jspm~
- [ ] ~Component: Line~
- [ ] ~Neaten SVG groups' hierarchy~
- [x] Rebuild scaffold
